env:
  global:
    - CODECOV_TOKEN=afc838ef-b7e6-4f63-a5cd-922982ac8ae7
language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install pytest-cov
install:
  - pip install ".[test]" . # install package + test dependencies
script:
  - pytest --doctest-modules --cov-report=xml --cov=host -v tests/    # run tests
after_success:
  - codecov # submit coverage
